os:
  - linux

language: java
jdk:
- openjdk8

branches:
  only:
  - master
  - dev
  - backend
  - staging

services:
  - docker

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"

before_script:
  - cd backend

script:
  - './gradlew clean build'
  - 'if [ "$TRAVIS_BRANCH" = "staging" ]; then bash ./travis/docker_deploy.sh; fi'