language: java
jdk:
- openjdk8
dist: trusty
branches:
  only:
  - master
  - dev
  - backend

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"

before_script: cd backend

script:
  # BUILD
  - "./gradlew clean build"
  
  # CONFIG
  - PRJ_GROUP=$(gradle properties -q | grep "group:" | awk '{print $2}')
  - PRJ_NAME=$(gradle properties -q | grep "name:" | awk '{print $2}')
  - PRJ_VERSION=$(gradle properties -q | grep "version:" | awk '{print $2}')
  - echo "## PROJECT_GROUP - ${PRJ_GROUP}"
  - echo "## PROJECT_NAME - ${PRJ_NAME}"
  - echo "## PROJECT_VERSION - ${PRJ_VERSION}"
  - PRJ_JAR=${PRJ_NAME}-${PRJ_VERSION}.ja
  
  # DOCKER
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker build -t ${PRJ_NAME}:${PRJ_VERSION} --build-arg JAR_FILE=build/libs/${PRJ_JAR} .
  - docker tag ${PRJ_NAME}:${PRJ_VERSION} ${DOCKER_USER}/${PRJ_NAME}:latest
  - docker push ${DOCKER_USER}/${PRJ_NAME}:latest
  