app:
  name: colletter

security:
  jwt:
    secret: colletter
    expires_in: 3600000
    header: Bearer

cloud:
  aws:
    s3:
      bucket: colletter
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  profiles:
    active: test
---
spring:
  profiles: develop
  datasource:
    develop:
      jdbc-url: jdbc:mysql://localhost:3306/colletter?serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
    generate-ddl: true
---
spring:
  profiles: test
  datasource:
    test:
      jdbc-url: jdbc:h2:mem:colletter
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
---
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder:
---


# Set base url
server:
  servlet:
    context-path: /api
  port: 8080
