spring:
  profiles:
    active: develop
---
spring:
  profiles: develop
  datasource:
    develop:
      jdbc-url: jdbc:mysql://localhost:3306/colletter?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate-ddl: true
---
spring:
  profiles: test
  datasource:
    test:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /console
---
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8080
